-- SELECT로 특정 데이터 추출하기
SELECT * FROM EMP;

-- WHERE 조건과 비교 연산자
SELECT * FROM EMP
WHERE SAL >=3000;

SELECT * FROM EMP
WHERE DEPTNO=10;

--급여가 1500이하인 사원의 사원번호, 사원 이름, 급여를 출력하는 SQL문 
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL<=1500;

-- 문자 데이터 조회 -> 저장된 데이터 값은 대소문자를 구분한다
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE ENAME = 'FORD';

-- 사원 이름이 SCOTT인 사원의 사원번호, 사원이름 , 급여 출력

SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE ENAME = 'SCOTT';

-- 날짜 데이터 조회
SELECT * FROM EMP
WHERE HIREDATE <= '1982/01/01';

-- 논리 연산자 AND, OR, NOT
SELECT * FROM EMP
WHERE DEPTNO =10
AND JOB = 'MANAGER';

SELECT * FROM EMP
WHERE DEPTNO =10
OR JOB = 'MANAGER';

--NOT 연산자
SELECT * FROM EMP
WHERE NOT DEPTNO = 10;

SELECT * FROM EMP
WHERE DEPTNO<>10;

--논리 연산자의 다양한 활용
SELECT * FROM EMP
WHERE SAL>=2000 AND SAL<=3000;

--커미션이 300 / 500/ 1400인 사원 검색
SELECT * FROM EMP
WHERE COMM=300 OR COMM=500 OR COMM =1400;

--BETWEEN AND 연산자
SELECT * FROM EMP
WHERE SAL>=2000 AND SAL<=3000;

SELECT * FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE HIREDATE BETWEEN '1987/01/01' AND '1987/12/31';

-- IN 연산자
SELECT * FROM EMP
WHERE COMM IN(300, 500, 1400);

SELECT * FROM EMP
WHERE EMPNO IN(7521, 7654, 7844);

SELECT * FROM EMP
WHERE COMM NOT IN(300, 500, 1400);

SELECT * FROM EMP
WHERE EMPNO<>7521 AND EMPNO<>7654 AND EMPNO<>7844;

SELECT * FROM EMP
WHERE EMPNO NOT IN(7521, 7654, 7844);

--와일드카드 (_) 사용하기
SELECT * FROM EMP
WHERE ENAME LIKE '_A%';

-- NOT LIKE 연산자
SELECT * FROM EMP
WHERE ENAME NOT LIKE '%A%';

--NULL 을 위한 연산자
SELECT * FROM EMP
WHERE COMM IS NULL;

SELECT * FROM EMP
WHERE COMM IS NOT NULL;

--정렬을 위한 ORDER BY 절
SELECT * FROM EMP
ORDER BY SAL ASC;

SELECT * FROM EMP
ORDER BY SAL DESC;