--<주요 함수>

--DUAL 테이블과 SQL 함수 분류
DESC DUAL

--절대값 구하는 ABS 함수
SELECT -10, ABS(-10)
FROM DUAL;

--소수점 아래를 버리는 FLOOR 함수
SELECT 34.5678, FLOOR(34.5678)
FROM DUAL;

-- 특정 자릿수에서 반올림하는 ROUND 함수
SELECT 34.5678, ROUND(34.5678)
FROM DUAL;

SELECT 34.5678, ROUND(34.5678, 2)
FROM DUAL;

SELECT 34.5678, ROUND(34.5678, -1)
FROM DUAL;

-- 특정한 자릿수에서 잘라내는 TRUNC 함수
SELECT TRUNC(34.5678, 2), TRUNC(34.5678, -1), TRUNC(34.5678)
FROM DUAL;

--나머지를 구하는 MOD함수
SELECT MOD(27,2), MOD(27,5), MOD(27,7)
FROM DUAL;

--사번이 홀수인 사람들 검색
SELECT * FROM EMP
WHERE MOD(EMPNO, 2)=1;

-- <문자 처리 함수>
-- 대문자 변환 UPPER
-- 소문자 변환 LOWER
-- 이니셜만 대문잦로 변환 INITCAP

-- 문자 길이를 구하는 LENGTG
SELECT LENGTH('Oracle'), LENGTH('오라클')
FROM DUAL;

-- 바이트 수를 알려주는 LENGTHB 함수
SELECT LENGTHB('ORACLE'), LENGTHB('오라클')
FROM DUAL;

-- 문자열 일부만 추출하는 SUBSTR  함수(대상, 시작위치, 추출 할 개수(바이트))
SELECT SUBSTR('WELCOME TO ORACLE', 4, 3)
FROM DUAL;

-- 특정 문자의 위치를 구하는 INSTR 함수대상, 찾을 글자, 시작위치, 몇번째 발견)
SELECT INSTR('WELCOME TO OREACLE', 'O')
FROM DUAL;

SELECT INSTR('WELCOME TO ORACLE', 'O' , 6, 2)
FROM DUAL;

--특정 기호로 채우는 LPAD/RPAD
SELECT LPAD('ORACLE', 20, '#')
FROM DUAL;

SELECT RPAD('ORACLE', 20, '#')
FROM DUAL;

--왼쪽에서 공백 문자를 삭제하는 LTRIM 함수
SELECT LTRIM('   ORACLE   ')
FROM DUAL;

--오른쪽에서 공백 문자를 삭제하는 RTRIM 함수
SELECT RTRIM('   ORACLE   ')
FROM DUAL;

-- 특정 문자를 잘라내는 TRIM 함수
SELECT TRIM(' ORACLE  ')
FROM DUAL;

-- <날짜 함수>

--현재 날짜를 반환하는 SYSDATE 함수
SELECT SYSDATE
FROM DUAL;

SELECT SYSDATE-1 "어제", SYSDATE "오늘", SYSDATE+1 "내일"
FROM DUAL;

-- 날짜에서 날짜 빼기도 가능, 각 사원들의 현재까지의 근무 일 수 ?
SELECT TRUNC(SYSDATE-HIREDATE) "근무일수"
FROM EMP;

-- 특정 기준으로 반올림 하는 ROUND 함수 - 달을 기준으로
SELECT HIREDATE, ROUND(HIREDATE, 'MONTH')
FROM EMP;

-- 특정 기준으로 버리는 TRUNC 함수
SELECT HIREDATE, ROUND(HIREDATE, 'MONTH')
FROM EMP;

-- 두 날짜사이의 간격을 나타내는 MONTHS_BETWEEN 함수
SELECT ENAME, SYSDATE, HIREDATE, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE))
FROM EMP;

--6 개월 수를 더하는 ADD_MONTHS 함수
SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE,6)
FROM EMP;

-- 해당 요일의 가장 가까운 날짜를 반환하는 NEXT_DAY함수
SELECT SYSDATE, NEXT_DAY(SYSDATE, '수요일')
FROM DUAL;

-- 해당 달의 마지막 날짜를 반환하는 LAST_DAY 함수
SELECT HIREDATE, LAST_DAY(HIREDATE)
FROM EMP;

-- <형변환 함수>
-- 문자형으로 변환하는 TO_CHAR 함수 , 날짜형을 문자형으로 변환하기
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD')
FROM DUAL;

SELECT HIREDATE, TO_CHAR(HIREDATE, 'YYYY/MM/DD DAY')
FROM EMP;
SELECT HIREDATE, TO_CHAR(HIREDATE, 'YYYY/MON/DD DY')
FROM EMP;

--현재 날짜와 시간을 출력하는 예제
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD, HH24:MI:SS')
FROM DUAL;

-- 날짜형으로 변환하는 TO_DATE함수 TO_DATE('문자', 'FORMAT')
SELECT ENAME, HIREDATE 
FROM EMP
WHERE HIREDATE=TO_DATE(19810220, 'YYYYMMDD');

SELECT TRUNC(SYSDATE-TO_DATE('2008/01/01', 'YYYY/MM/DD'))
FROM DUAL;

--숫자형으로 변환하는 TO_NUMBER 함수
SELECT TO_NUMBER('20,000', '99,999') - TO_NUMBER('10,000' , '99,999')
FROM DUAL;

--NULL 값을 다른 값으로 변환하는 NVL 함수
SELECT ENAME, SAL, COMM, SAL*12+COMM,NVL(COMM, 0), SAL*12+NVL(COMM, 0)
FROM EMP;

SELECT EMPNO, ENAME, NVL(TO_CHAR(MGR, '9999'),'CEO') "MANAGER"
FROM EMP
WHERE MGR IS NULL;

SELECT NVL2(COMM, SAL*12+COMM, SAL*12)
FROM EMP;

-- 선택을 위한 DECODE 함수
SELECT ENAME, DEPTNO,
DECODE(DEPTNO, 10, 'ACCOUNTNG',
                20, 'RESEARCH',
                30,'SALES',
                40, 'OPERATIONS')
                AS DNAME
FROM EMP;

SELECT EMPNO, JOB, SAL, 
DECODE(JOB, 'ANALYST', SAL*1.05,
            'SALESMAN', SAL*1.1,
            'MANAGER', SAL*1.15,
            'CLERK', SAL*1.2) "UPSAL"
FROM EMP;

-- 조건에 따라 서로 다른 처리가 가능한 CASE 함수, 범위 지정이 가능하다
SELECT ENAME, DEPTNO,
CASE WHEN DEPTNO=10 THEN'ACCOUNTING'
    WHEN DEPTNO=20 THEN 'RESEARCH'
    WHEN DEPTNO=30 THEN 'SALES'
    WHEN DEPTNO=40 THEN 'OPERATIONS'
    END "DNAME"
    FROM EMP;