--합계를 구하는 SUM함수,칼럼값NULL은 제외하고 계산
SELECT SUM(SAL)
FROM EMP;

SELECT SUM(COMM)
FROM EMP;

--평균을 구하는 AVG 함수, 칼럼값NULL은 제외하고 계산
SELECT AVG(SAL)
FROM EMP;

--최대값 구하는 MAX, 최소값 구하는 MIN 함수
SELECT MAX(SAL),MIN(SAL)
FROM EMP;

--단일 그룹의 그룹함수가 아닐 경우 >>오류 발생
SELECT ENAME, MAX(SAL)
FROM EMP;

-- 같이 출력하려면? 서브쿼리
SELECT ENAME, SAL
FROM EMP
WHERE SAL=(SELECT MAX(SAL)FROM EMP);

--예제, 가장 최근에 입사한 사원의 입사일/ 가장 오래된 입사일 
SELECT MAX(HIREDATE)"최근 입사일", MIN(HIREDATE)"최초 입사일"
FROM EMP;

--로우 개수를 구하는 COUNT 함수>>
SELECT COUNT(COMM)
FROM EMP;

--COUNT 함수는 NULL값에 대해 개수를 세지 않는다, COUNT(*)활용
SELECT COUNT(*), COUNT(COMM)
FROM EMP;

--예제, 10번 부서 소속 사원 중 커미션을 받는 사원의 수?
SELECT COUNT(COMM)"사원 수"
FROM EMP
WHERE DEPTNO=10;

--사원 테이블에서 사원들의 직업 개수
SELECT COUNT(JOB)"업무 수"
FROM EMP;

--중복행 제거 키워드를 활용한 COUNT 함수/ 직업의 종류?
SELECT COUNT(DISTINCT JOB)
FROM EMP;

--GROUP BY 절
SELECT DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO,AVG(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, MAX(SAL), MIN(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT DEPTNO, COUNT(*), COUNT(COMM)
FROM EMP
GROUP BY DEPTNO;

--HAVING 조건
SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL)>= 2000;

SELECT DEPTNO, MAX(SAL), MIN(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING MAX(SAL)>=2900;

--예제 문제 
--1
SELECT MAX(SAL)"최고액-MAXIMUM", MIN(SAL)"최저액-MINIMUM", SUM(SAL)"총액-SUM", ROUND(AVG(SAL))"평균 급여 -AVERAGE'"
FROM EMP;
--2
SELECT JOB, MAX(SAL)"최고액-MAXIMUM", MIN(SAL)"최저액-MINIMUM", SUM(SAL)"총액-SUM", ROUND(AVG(SAL))"평균 급여 -AVERAGE'"
FROM EMP
GROUP BY JOB;
--3
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB;
--4
SELECT COUNT(JOB)
FROM EMP
WHERE JOB='MANAGER';

--5
SELECT MAX(SAL)-MIN(SAL) "DIFFERENCE"
FROM EMP;

--6
SELECT JOB, MIN(SAL)
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY JOB
HAVING NOT MIN(SAL)<2000
ORDER BY MIN(SAL)DESC;

--7
SELECT DEPTNO "DNO", COUNT(*)"NUMER OF PEOPLE", ROUND(AVG(SAL),2)"SALARY"
FROM EMP
GROUP BY DEPTNO;

--8
SELECT 
    DECODE(DEPTNO,10, 'ACCOUNTING',
                  20, 'RESEARCH',
                  30, 'SALES',
                  40, 'OPERATIONS')"DNAME",
    DECODE(DEPTNO,10, 'NEW YORK',
                  20, 'DALLAS',
                  30, 'CHICAGO',
                  40, 'BOSTON') "LOCATION",
    COUNT(*)AS "NUMBER OF PEOPLE",
    ROUND(AVG(SAL))"SALARY"
FROM EMP
GROUP BY DEPTNO;

--9
SELECT JOB,
        SUM(DECODE(DEPTNO, 10, SAL)) "부서 10",
        SUM(DECODE(DEPTNO, 20, SAL)) "부서 20",
        SUM(DECODE(DEPTNO, 30, SAL)) "부서 30",
        SUM(SAL)"총액"
FROM EMP
GROUP BY JOB;
